[book]
authors = ["Michael"]
language = "en"
# multilingual = false
src = "src"
title = "Algebraeon Rust Library User Guide"

[output.html]
mathjax-support = true

[output.html.playground]
runnable = false
